let
    // Read the first cell
    Source = Excel.CurrentWorkbook(){0}[Content],
    RawText = Source{0}[Sütun1],

    // Split into logical rows using code anchor
    SplitRows = Text.Split(RawText, "04.KTB."),
    RowsTable = Table.FromList(SplitRows, Splitter.SplitByNothing(), {"Text"}),
    RemoveEmpty = Table.SelectRows(RowsTable, each [Text] <> ""),
    AddPrefix = Table.TransformColumns(
        RemoveEmpty,
        {{"Text", each Text.Trim("04.KTB." & _), type text}}
    ),

    // Remove line breaks inside descriptions
    CleanText = Table.TransformColumns(
        AddPrefix,
        {{"Text", each Text.Replace(Text.Replace(_, "#(lf)", " "), "#(cr)", " "), type text}}
    ),

    // PRICE = last token
    AddPrice = Table.AddColumn(
        CleanText,
        "Price",
        each Text.Reverse(
            Text.BeforeDelimiter(Text.Reverse([Text]), " ")
        )
    ),

    // Remove price from text
    RemovePrice = Table.AddColumn(
        AddPrice,
        "NoPrice",
        each Text.Trim(Text.BeforeDelimiter([Text], [Price]))
    ),

    // UNIT = last token of remaining text
    AddUnit = Table.AddColumn(
        RemovePrice,
        "Unit",
        each Text.Reverse(
            Text.BeforeDelimiter(Text.Reverse([NoPrice]), " ")
        )
    ),

    // Remove unit
    RemoveUnit = Table.AddColumn(
        AddUnit,
        "CoreText",
        each Text.Trim(Text.BeforeDelimiter([NoPrice], [Unit]))
    ),

    // CODE = first token
    AddCode = Table.AddColumn(
        RemoveUnit,
        "Code",
        each Text.BeforeDelimiter([CoreText], " ")
    ),

    // DESCRIPTION = everything after code
    AddDescription = Table.AddColumn(
        AddCode,
        "Description",
        each Text.Trim(Text.AfterDelimiter([CoreText], " "))
    ),

    // Final output
    Result = Table.SelectColumns(
        AddDescription,
        {"Code", "Description", "Unit", "Price"}
    )
in
    Result
